# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1494, 792)
        Form.setAutoFillBackground(False)
        self.source = QtWidgets.QLabel(Form)
        self.source.setGeometry(QtCore.QRect(120, 90, 431, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source.sizePolicy().hasHeightForWidth())
        self.source.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.source.setFont(font)
        self.source.setScaledContents(False)
        self.source.setAlignment(QtCore.Qt.AlignCenter)
        self.source.setObjectName("source")
        self.request = QtWidgets.QLabel(Form)
        self.request.setGeometry(QtCore.QRect(870, 90, 511, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.request.sizePolicy().hasHeightForWidth())
        self.request.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.request.setFont(font)
        self.request.setAlignment(QtCore.Qt.AlignCenter)
        self.request.setObjectName("request")
        self.button = QtWidgets.QPushButton(Form)
        self.button.setGeometry(QtCore.QRect(450, 660, 141, 71))
        self.button.setObjectName("button")
        self.button2 = QtWidgets.QPushButton(Form)
        self.button2.setGeometry(QtCore.QRect(830, 660, 141, 71))
        self.button2.setObjectName("button2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.source.setText(_translate("Form", "原始图片"))
        self.request.setText(_translate("Form", "结果展示"))
        self.button.setText(_translate("Form", "上传图片"))
        self.button2.setText(_translate("Form", "一键检测"))
